prometheus:
  metrics:
    node:
      status: "kube_node_status_condition==1"
    cpu:
      total: "sum(kube_node_status_capacity{resource=\"cpu\", ${NODE_FILTER} })"
      usage: |
        sum by (node) (
          label_replace(
            rate(node_cpu_seconds_total{mode!="idle"}[5m]),
            "internal_ip",
            "$1",
            "instance",
            "(.*):[0-9]+"
          )
          * on(internal_ip) group_left(node) kube_node_info{${NODE_FILTER}}
        )
      usage_namespace: |
        sum by (namespace) (
          rate(container_cpu_usage_seconds_total{
            container!~"POD|", 
            container!="", 
            ${NODE_FILTER}, ${NAMESPACE_FILTER}}[5m])
        )
      request: "sum by(node) (kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",${NODE_FILTER},${NAMESPACE_FILTER} })"
      limit: "sum by(node) (kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",${NODE_FILTER},${NAMESPACE_FILTER} })"
      load5:  |
        sum by (node) (
          sum by (internal_ip) (
            label_replace(
              node_load5,
              "internal_ip",
              "$1",
              "instance",
              "(.*):[0-9]+"
            )
          )
          * on(internal_ip) group_left(node) kube_node_info{${NODE_FILTER}}
        )
    memory:
      total: "sum(kube_node_status_capacity{resource=\"memory\", ${NODE_FILTER} })"
      usage: "sum by (node) (container_memory_usage_bytes{${NODE_FILTER}, ${NAMESPACE_FILTER}}) "
      usage_namespace: |
        sum by (namespace) (
          container_memory_usage_bytes{
            container!~"POD|", 
            container!="", ${NODE_FILTER}, ${NAMESPACE_FILTER}
          }
        ) 
      request: "sum by(node) (kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",${NODE_FILTER},${NAMESPACE_FILTER} })"
      limit: "sum by(node) (kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",${NODE_FILTER},${NAMESPACE_FILTER} })"
    filesystem:
      total: |
        sum (
             sum by (internal_ip) (
               label_replace(
                 node_filesystem_size_bytes{fstype=~"ext4|xfs|btrfs", mountpoint="/"},
                 "internal_ip",
                 "$1",
                 "instance",
                 "(.*):[0-9]+"
               )
             )
             * on(internal_ip) group_left(node) kube_node_info{${NODE_FILTER}}
           ) 
      usage: |
        sum by(node) (
                  sum by (internal_ip) (
                    label_replace(
                      sum by (instance, device) (node_filesystem_size_bytes{fstype=~"ext4|xfs|btrfs", mountpoint="/"}-node_filesystem_free_bytes{fstype=~"ext4|xfs|btrfs", mountpoint="/"}),
                      "internal_ip",
                      "$1",
                      "instance",
                      "(.*):[0-9]+"
                    )
                  )
                  * on(internal_ip) group_left(node) kube_node_info{${NODE_FILTER}}
                ) 
      usage_namespace: "sum by(namespace) (kubelet_volume_stats_used_bytes {}) "
    disk:
      read_bytes: |
        sum by (node) (
          sum by (internal_ip) (
            label_replace(
              rate(node_disk_read_bytes_total{}[5m]),
              "internal_ip",
              "$1",
              "instance",
              "(.*):[0-9]+"
            )
          )
          * on(internal_ip) group_left(node) kube_node_info{${NODE_FILTER}}
        )
      write_bytes: |
        sum by (node) (
          sum by (internal_ip) (
            label_replace(
              rate(node_disk_written_bytes_total{}[5m]),
              "internal_ip",
              "$1",
              "instance",
              "(.*):[0-9]+"
            )
          )
          * on(internal_ip) group_left(node) kube_node_info{${NODE_FILTER}}
        ) 
    network:
      receive_bytes: |
        sum by (node) (
          sum by (internal_ip) (
            label_replace(
              rate(node_network_receive_bytes_total{device!="lo"}[5m]),
              "internal_ip",
              "$1",
              "instance",
              "(.*):[0-9]+"
            )
          )
          * on(internal_ip) group_left(node) kube_node_info{${NODE_FILTER}}
        )
      transmit_bytes : |  
        sum by (node) (
          sum by (internal_ip) (
            label_replace(
              rate(node_network_transmit_bytes_total{device!="lo"}[5m]),
              "internal_ip",
              "$1",
              "instance",
              "(.*):[0-9]+"
            )
          )
          * on(internal_ip) group_left(node) kube_node_info{${NODE_FILTER}}
        )
      receive_drop : |   
          sum by (node) (
          sum by (internal_ip) (
            label_replace(
              rate(node_network_receive_drop_total{}[5m]),
              "internal_ip",
              "$1",
              "instance",
              "(.*):[0-9]+"
            )
          )
          * on(internal_ip) group_left(node) kube_node_info{${NODE_FILTER}}
          )
      transmit_drop: |
        sum by (node) (
          sum by (internal_ip) (
            label_replace(
              rate(node_network_transmit_drop_total{}[5m]),
              "internal_ip",
              "$1",
              "instance",
              "(.*):[0-9]+"
            )
          )
          * on(internal_ip) group_left(node) kube_node_info{${NODE_FILTER}}
        )
      receive_err: |
        sum by (node) (
          sum by (internal_ip) (
            label_replace(
              rate(node_network_receive_errs_total{}[5m]),
              "internal_ip",
              "$1",
              "instance",
              "(.*):[0-9]+"
            )
          )
          * on(internal_ip) group_left(node) kube_node_info{${NODE_FILTER}}
        )
      transmit_err: |
        sum by (node) (
          sum by (internal_ip) (
            label_replace(
              rate(node_network_transmit_errs_total{}[5m]),
              "internal_ip",
              "$1",
              "instance",
              "(.*):[0-9]+"
            )
          )
          * on(internal_ip) group_left(node) kube_node_info{${NODE_FILTER}}
        )
    gpu:
      total: "gpu_operator_gpu_nodes_total"
      usage_namespace: |
        kube_pod_container_resource_requests{resource="nvidia_com_gpu"}
        * on(namespace, pod)
          group_left()
          (kube_pod_status_phase{phase!="Pending", job="kube-state-metrics"} == 1)
      request: "sum by(node) (kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\",${NODE_FILTER},${NAMESPACE_FILTER} })"
      limit: "sum by(node) (kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\",${NODE_FILTER},${NAMESPACE_FILTER} })"
      util: "nvidia_smi_utilization_gpu_ratio * 100"
      memory_copy_util: "nvidia_smi_utilization_memory_ratio * 100"
      memory_used: "nvidia_smi_memory_used_bytes / 1048576"
      memory_total: "nvidia_smi_memory_total_bytes / 1048576"
      temperature: "nvidia_smi_temperature_gpu"
      power_draw: "nvidia_smi_power_draw_watts"
    pod:
      total: "sum(kube_node_status_capacity{resource=\"pods\", ${NODE_FILTER} })"
      used_node: "kubelet_running_pods{${NODE_FILTER}}"
      usage_namespace: "count(kube_pod_info{${NODE_FILTER}}) by (namespace)"
    top5: 
      cpu: "topk(5, sum by (node) (rate(container_cpu_usage_seconds_total{${NODE_FILTER},${NAMESPACE_FILTER}}[5m]))) by (node)"
      memory: "topk(5, sum by (node) (container_memory_usage_bytes{${NODE_FILTER},${NAMESPACE_FILTER}})) by (node) " 
      disk: "topk(5, sum by (node) (kubelet_volume_stats_used_bytes{${NODE_FILTER},${NAMESPACE_FILTER}})) by (node) "
      filesystem: |
        topk(5, sum by(node) (
                    sum by (internal_ip) (
                      label_replace(
                        sum by (instance, device) (node_filesystem_size_bytes{fstype=~"ext4|xfs|btrfs", mountpoint="/"}-node_filesystem_free_bytes{fstype=~"ext4|xfs|btrfs", mountpoint="/"}),
                        "internal_ip",
                        "$1",
                        "instance",
                        "(.*):[0-9]+"
                      )
                    )
                    * on(internal_ip) group_left(node) kube_node_info{${NODE_FILTER}}
                  ) 
      pod: "topk(5, count(kube_pod_info{${NODE_FILTER},${NAMESPACE_FILTER}}) by (node)) by (node)"
      gpu: "topk(5, sum by (node) (kube_pod_container_resource_requests{resource='nvidia_com_gpu',${NODE_FILTER},${NAMESPACE_FILTER}})) by (node)"
    tpu: 
      total: "gke_tpu_node_total"
      chip_total: "gke_tpu_chip_total"
      allocated_total: "gke_cluster_tpu_allocated"
      available_total: "gke_cluster_tpu_available"
      cpu_usage: "gke_tpu_node_usage{resource_type=\"cpu\", ${NODE_FILTER}}"
      memory_usage: "gke_tpu_node_usage{resource_type=\"memory\", ${NODE_FILTER}}"
      tpu_usage: "gke_tpu_node_usage{resource_type=\"tpu\", ${NODE_FILTER}}"
      ephemeral_storage_usage: "gke_tpu_node_usage{resource_type=\"ephemeral_storage\"}, ${NODE_FILTER}}"
      capacity_total: "gke_tpu_node_capacity{${NODE_FILTER}}"
    monitoring:
      helm_releases: "count(helm_chart_info{description!~\".*failed.*\"}) or vector(0)"
      gpu_count: "count(nvidia_smi_gpu_info) or vector(0)"
      gpu_avg_util: "avg(nvidia_smi_utilization_gpu_ratio) * 100 or vector(0)"
      active_alerts: "count(ALERTS{alertstate=\"firing\"}) or vector(0)"
      release_status: |
        helm_chart_info{description!~".*failed.*"}
    cost:
      gpu_usage_by_ns: |
        sum by (namespace) (kube_pod_container_resource_requests{resource="nvidia_com_gpu"}) or vector(0)
      gpu_count_by_ns: |
        sum by (namespace) (kube_pod_container_resource_requests{resource="nvidia_com_gpu"}) or vector(0)
      gpu_util_range: |
        sum by (namespace) (kube_pod_container_resource_requests{resource="nvidia_com_gpu"})

      